export const StudentData = [
    {
        name: "방성훈",
        imageSrc: "https://t4.ftcdn.net/jpg/03/64/21/11/360_F_364211147_1qgLVxv1Tcq0Ohz3FawUfrtONzz8nq3e.jpg",
        sex: "남자",
        phone: "010-1234-5678",
        major: "정보통신과",
        middleSchoolGraduation: "2019-02-01",
        highSchoolAdmission: "2020-03-02",
        grade: "3학년",
        class: "3반",
        number: "1번",
        club: "독서동아리",
        history: [
            {major: "정보통신과", class: "3반", number: "1번", homeroomTeacher: "김이박"},
            {major: "정보통신과", class: "1반", number: "5번", homeroomTeacher: "홍길동"},
            {major: "정보통신과", class: "3반", number: "1번", homeroomTeacher: "이천주"},
        ]
    },
    {
        name: "장성윤",
        imageSrc: "https://media.istockphoto.com/id/1338134336/photo/headshot-portrait-african-30s-man-smile-look-at-camera.jpg?b=1&s=170667a&w=0&k=20&c=j-oMdWCMLx5rIx-_W33o3q3aW9CiAWEvv9XrJQ3fTMU=",
        sex: "남자",
        phone: "010-1234-5678",
        major: "소프트웨어과",
        middleSchoolGraduation: "2001-02-02",
        highSchoolAdmission: "2017-03-03",
        grade: "3학년",
        class: "2반",
        number: "1번",
        club: "독서동아리",
        history: [
            {major: "정보통신과", class: "3반", number: "6번", homeroomTeacher: "김이박"},
            {major: "소프트웨어과", class: "1반", number: "12번", homeroomTeacher: "홍길동"},
            {major: "소프트웨어과", class: "2반", number: "1번", homeroomTeacher: "도바킨"},
        ]
    },
    {
        name: "정경빈",
        imageSrc: "https://expertphotography.b-cdn.net/wp-content/uploads/2020/08/profile-photos-4.jpg",
        sex: "여자",
        phone: "010-1234-5678",
        major: "소프트웨어과",
        middleSchoolGraduation: "2012-12-12",
        highSchoolAdmission: "2022-02-22",
        grade: "1학년",
        class: "2반",
        number: "3번",
        club: "영화감상동아리",
        history: [
            {major: "소프트웨어과", class: "2반", number: "3번", homeroomTeacher: "아무개"},
            {major: "", class: "", number: "", homeroomTeacher: ""},
            {major: "", class: "", number: "", homeroomTeacher: ""},
        ]
    },
    {
        name: "김찬",
        imageSrc: "https://pbs.twimg.com/profile_images/1485050791488483328/UNJ05AV8_400x400.jpg",
        sex: "남자",
        phone: "010-1234-5678",
        major: "소프트웨어과",
        middleSchoolGraduation: "2010-10-10",
        highSchoolAdmission: "2011-11-11",
        grade: "2학년",
        class: "2반",
        number: "1번",
        club: "영화감상동아리",
        history: [
            {major: "소프트웨어과", class: "2반", number: "3번", homeroomTeacher: "도바킨"},
            {major: "소프트웨어과", class: "2반", number: "1번", homeroomTeacher: "호카게"},
            {major: "", class: "", number: "", homeroomTeacher: ""},
        ]
    },
    {
        name: "이수범",
        imageSrc: "https://images.pexels.com/photos/220453/pexels-photo-220453.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
        sex: "남자",
        phone: "010-1234-5678",
        major: "소프트웨어과",
        middleSchoolGraduation: "2008-03-30",
        highSchoolAdmission: "2016-09-19",
        grade: "1학년",
        class: "1반",
        number: "1번",
        club: "초현상특무동아리",
        history: [
            {major: "소프트웨어과", class: "1반", number: "1번", homeroomTeacher: "우로코다키상"},
            {major: "", class: "", number: "", homeroomTeacher: ""},
            {major: "", class: "", number: "", homeroomTeacher: ""},
        ]
    },
    {
        name: "이수범",
        imageSrc: "https://images.pexels.com/photos/220453/pexels-photo-220453.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
        sex: "남자",
        phone: "010-1234-5678",
        major: "소프트웨어과",
        middleSchoolGraduation: "2008-03-30",
        highSchoolAdmission: "2016-09-19",
        grade: "1학년",
        class: "1반",
        number: "1번",
        club: "초현상특무동아리",
        history: [
            {major: "소프트웨어과", class: "1반", number: "1번", homeroomTeacher: "우로코다키상"},
            {major: "", class: "", number: "", homeroomTeacher: ""},
            {major: "", class: "", number: "", homeroomTeacher: ""},
        ]
    },
    {
        name: "이수범",
        imageSrc: "https://images.pexels.com/photos/220453/pexels-photo-220453.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
        sex: "남자",
        phone: "010-1234-5678",
        major: "소프트웨어과",
        middleSchoolGraduation: "2008-03-30",
        highSchoolAdmission: "2016-09-19",
        grade: "1학년",
        class: "1반",
        number: "1번",
        club: "초현상특무동아리",
        history: [
            {major: "소프트웨어과", class: "1반", number: "1번", homeroomTeacher: "우로코다키상"},
            {major: "", class: "", number: "", homeroomTeacher: ""},
            {major: "", class: "", number: "", homeroomTeacher: ""},
        ]
    },
    {
        name: "이수범",
        imageSrc: "https://images.pexels.com/photos/220453/pexels-photo-220453.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
        sex: "남자",
        phone: "010-1234-5678",
        major: "소프트웨어과",
        middleSchoolGraduation: "2008-03-30",
        highSchoolAdmission: "2016-09-19",
        grade: "1학년",
        class: "1반",
        number: "1번",
        club: "초현상특무동아리",
        history: [
            {major: "소프트웨어과", class: "1반", number: "1번", homeroomTeacher: "우로코다키상"},
            {major: "", class: "", number: "", homeroomTeacher: ""},
            {major: "", class: "", number: "", homeroomTeacher: ""},
        ]
    },
    {
        name: "이수범",
        imageSrc: "https://images.pexels.com/photos/220453/pexels-photo-220453.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
        sex: "남자",
        phone: "010-1234-5678",
        major: "소프트웨어과",
        middleSchoolGraduation: "2008-03-30",
        highSchoolAdmission: "2016-09-19",
        grade: "1학년",
        class: "1반",
        number: "1번",
        club: "초현상특무동아리",
        history: [
            {major: "소프트웨어과", class: "1반", number: "1번", homeroomTeacher: "우로코다키상"},
            {major: "", class: "", number: "", homeroomTeacher: ""},
            {major: "", class: "", number: "", homeroomTeacher: ""},
        ]
    },
    {
        name: "이수범",
        imageSrc: "https://images.pexels.com/photos/220453/pexels-photo-220453.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
        sex: "남자",
        phone: "010-1234-5678",
        major: "소프트웨어과",
        middleSchoolGraduation: "2008-03-30",
        highSchoolAdmission: "2016-09-19",
        grade: "1학년",
        class: "1반",
        number: "1번",
        club: "초현상특무동아리",
        history: [
            {major: "소프트웨어과", class: "1반", number: "1번", homeroomTeacher: "우로코다키상"},
            {major: "", class: "", number: "", homeroomTeacher: ""},
            {major: "", class: "", number: "", homeroomTeacher: ""},
        ]
    }
]